apiVersion: v1
kind: Service
metadata:
  name: nextjs-app
  labels:
    app: nextjs-app
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
